export const REQUEST_CREATE_NEW_USER = 'app/SignUpPage/REQUEST_CREATE_NEW_USER'
export const CREATE_NEW_USER_SUCCESS = 'app/SignUpPage/CREATE_NEW_USER_SUCCESS'
export const CREATE_NEW_USER_FAILED = 'app/SignUpPage/CREATE_NEW_USER_FAILED'
